import type { Dict } from './pt';

export const en: Dict = {
  lang: 'en', htmlLang: 'en', locale: 'en_US', language: { switchPt: 'Switch to Portuguese', switchEn: 'Switch to English' }, brand: 'Aymar, home', ui: { languageSelector: 'Language selector', openMenu: 'Open menu', closeMenu: 'Close menu', phone: 'operation', live: 'live', dataToday: 'operation / today / data', revenue: 'revenue', automation: 'automation', receivedTime: '15:03', sentTime: '15:04 ✓✓' },
  metadata: { title: 'Aymar — applied technology', description: 'Custom software, unified data and applied AI for operations that need to move.' },
  loader: 'loading operation',
  nav: { studio: 'studio', work: 'work', process: 'process', how: 'how it works', specialist: 'specialist', contact: 'contact', cta: "let's talk ↗", menu: 'menu' },
  hero: { eyebrow: 'custom software · unified data · applied ai', title: 'The smart operation', emphasis: 'behind it all.', paragraph: 'We build the engine that runs your business. Software made to measure, data that actually talks to itself, and AI that takes over the steps nobody should be doing by hand.', cta: 'talk to a specialist ↗', location: 'Brazil — remote' },
  marquee: { first: 'custom software ✳ unified data ✳ applied ai ✳ operations automation ✳ landing pages ✳ made-to-measure product ✳', second: 'technology arrives before the problem ✳' },
  studio: { eyebrow: '01 the studio', title: 'Software, data and AI', emphasis: 'in one operation.', paragraph: 'Aymar is an applied technology studio. We step in where the spreadsheet, the email thread and the meeting became the product — and hand it back as software, data and AI that works on its own.' },
  work: { eyebrow: '02 work', editorialBefore: 'A landing page is the front door — what stays after is the operation: the dashboard, the clean data, the automation that runs with nobody watching. Below, a sample of pages delivered in partnership with ', editorialLink: 'Agência PKG ↗', editorialAfter: '.', hover: 'Hover to see it live, click to open.', preview: 'preview' },
  process: { eyebrow: '03 process', title: 'Three things', emphasis: 'done right.', items: [{ title: 'Custom software', text: 'Made-to-measure systems — landing pages, dashboards, internal products. No off-the-shelf framework, no plugin that breaks in three months.' }, { title: 'Unified data', text: 'We plug what you already use into a single layer. One place where sales, marketing and operations see the same truth.' }, { title: 'Applied AI', text: 'Models that run real steps of your process. Not a chatbot in the footer — an agent that opens tickets, writes emails, updates the CRM.' }] },
  how: { eyebrow: '04 how it works', title: 'From operational chaos', emphasis: 'to running itself.', paragraph: 'You do not need to know what to build. You need to know what is stuck. We translate that into a system — and get out of the way once it starts running.', beforeLabel: 'BEFORE', beforeTitle: 'The operation lives in seven places.', before: [{ tool: 'excel', text: 'A spreadsheet three people edit at once' }, { tool: 'whatsapp', text: 'An order that arrives on WhatsApp and gets lost' }, { tool: 'gmail', text: 'An approval buried in email' }, { tool: 'trello', text: 'A card nobody has moved in two weeks' }, { tool: 'sheets', text: 'A report built by hand every Monday' }], afterLabel: 'AFTER', afterTitle: 'One operation, one source of truth.', after: ['A dashboard where everyone sees the same number', 'An order enters through WhatsApp and lands in the system', 'One-tap approval, recorded and traceable', 'A report that builds itself every Monday at 7am'], disclaimer: 'TRADEMARKS BELONG TO THEIR RESPECTIVE OWNERS.', steps: [{ number: '01', title: 'Diagnosis', timeframe: '1 to 3 days', text: 'A call and read-only access to what you already use. We map where time leaks and what each manual hour costs — before proposing anything.', deliverable: 'a map of the current process and the cost of waste.' }, { number: '02', title: 'Solution design', timeframe: '3 to 5 days', text: 'We define what is software, automation and AI. Fixed scope, fixed price, fixed timeline. No surprise extra hours.', deliverable: 'scope, clickable prototype and fixed-price proposal.' }, { number: '03', title: 'Build', timeframe: '2 to 6 weeks', text: 'Weekly deliveries you can already use. No disappearing for two months and returning with a system you did not ask for.', deliverable: 'access from week one and adjustments with every delivery.' }, { number: '04', title: 'Running itself', timeframe: 'ongoing', text: 'We train your team, document and monitor. The system is yours — code, data and access. No vendor lock-in.', deliverable: 'code, documentation and support included in the first month.' }], closing: 'If you are not using something within two weeks, we got the diagnosis wrong — and we redo it.', cta: 'start with a diagnosis ↗' },
  specialist: { eyebrow: '05 specialist', title: 'Software, AI and automation', emphasis: 'already running.', paragraph: 'More than 20 projects delivered in custom software, applied AI and operations automation. Below, three flows we built — live simulation, the way they run in production.', stats: [{ value: '+20', label: 'projects delivered' }, { value: '03', label: 'fronts — software, ai, automation' }, { value: '02', label: 'business days to reply' }], tabs: [{ label: '01 WHATSAPP CHATBOT', text: 'Customer sends a message, the bot qualifies, books and pushes to the CRM. Nobody on the team touches it.' }, { label: '02 REPETITIVE AI', text: 'The AI reads, classifies and fills in what used to be copy and paste. Runs overnight.' }, { label: '03 OPERATIONS DASHBOARD', text: 'Sales, operations and finance in the same dashboard. One number, one source of truth.' }], demo: 'DEMO', cta: 'Talk to a specialist →', note: 'REPLIES ON WHATSAPP · MON–FRI, BUSINESS HOURS', chatbot: { customer: ["Hi, I'd like a quote", 'Automation', "Order entry, it's all manual"], bot: ['Of course! Is it for custom software, AI or automation?', 'Perfect. Which process is slowing you down today?', 'Got it. Booked you with a specialist: Thursday, 3pm. ✓'] }, repetitive: { rows: ['invoice', 'customer record', 'reconciliation', 'collection email', 'update CRM', 'report'], counter: 'RECORDS PROCESSED TODAY' }, dashboard: { currency: 'R$184.2K', percent: '92%' } },
  contact: { eyebrow: '06 contact', title: 'Got an operation', emphasis: 'to fix?', paragraph: "Write directly: tell us which process is stuck and what you've already tried. A real person replies, within two business days.", instagram: 'instagram ↗', pkg: 'pkg partnership ↗', brief: 'send a brief ↗' },
  footer: { contact: 'contact', social: 'social', studio: 'studio', location: 'BRAZIL, REMOTE', copy: '© 2026 Aymar · technology arrives before the problem.' },
  whatsapp: "Hi! I came from the Aymar website. I'd like to talk about my company's operation.", mailSubject: 'Aymar proposal',
  projects: [{ title: 'Criar SaaS', meta: 'digital product · lead capture', badge: 'saas launch', category: 'digital product · lead capture' }, { title: 'Dra. Aline Azevedo – Odontologia', meta: 'dentistry · authority', badge: 'landing page', category: 'dentistry · authority' }, { title: 'Copie AI', meta: 'ai · launch', badge: 'ai launch', category: 'ai · launch' }, { title: 'Jessica Moraes – O Mapa', meta: 'info product · conversion', badge: 'landing page', category: 'info product · conversion' }, { title: 'Master Class', meta: 'event · registration', badge: 'event page', category: 'event · registration' }, { title: 'Mentoria Caio Martins', meta: 'mentorship · high ticket', badge: 'sales page', category: 'mentorship · high ticket' }, { title: 'Isaque Mota', meta: 'personal brand · conversion', badge: 'landing page', category: 'personal brand · conversion' }, { title: 'Primeira Assinatura em 24h', meta: 'digital product · conversion', badge: 'sales page', category: 'digital product · conversion' }]
};
