import type { Dict } from './pt';

export const en: Dict = {
  lang: 'en', htmlLang: 'en', locale: 'en_US', language: { switchPt: 'Switch to Portuguese', switchEn: 'Switch to English' }, brand: 'Aymar, home', ui: { languageSelector: 'Language selector', openMenu: 'Open menu', closeMenu: 'Close menu', phone: 'operation', live: 'live', dataToday: 'operation / today / data', revenue: 'revenue', automation: 'automation', receivedTime: '15:03', sentTime: '15:04 ✓✓' },
  metadata: { title: 'aymar — applied technology', description: 'Custom software, unified data and applied AI for operations that need to move.' },
  loader: 'loading operation',
  nav: { studio: 'studio', work: 'work', process: 'process', specialist: 'specialist', contact: 'contact', cta: "let's talk ↗", menu: 'menu' },
  hero: { eyebrow: 'custom software · unified data · applied ai', title: 'The smart operation', emphasis: 'behind it all.', paragraph: 'We build the engine that runs your business. Software made to measure, data that actually talks to itself, and AI that takes over the steps nobody should be doing by hand.', cta: 'talk to a specialist ↗', location: 'Brazil — remote' },
  marquee: { first: 'custom software ✳ unified data ✳ applied ai ✳ operations automation ✳ landing pages ✳ made-to-measure product ✳', second: 'technology arrives before the problem ✳' },
  studio: { eyebrow: '01 the studio', title: 'Software, data and AI', emphasis: 'in one operation.', paragraph: 'aymar is an applied technology studio. We step in where the spreadsheet, the email thread and the meeting became the product — and hand it back as software, data and AI that works on its own.' },
  work: { eyebrow: '02 work', editorialBefore: 'A landing page is the front door — what stays after is the operation: the dashboard, the clean data, the automation that runs with nobody watching. Below, a sample of pages delivered in partnership with ', editorialLink: 'Agência PKG ↗', editorialAfter: '.', hover: 'Hover to see it live, click to open.', preview: 'preview' },
  process: { eyebrow: '03 process', title: 'Three things', emphasis: 'done right.', items: [{ title: 'Custom software', text: 'Made-to-measure systems — landing pages, dashboards, internal products. No off-the-shelf framework, no plugin that breaks in three months.' }, { title: 'Unified data', text: 'We plug what you already use into a single layer. One place where sales, marketing and operations see the same truth.' }, { title: 'Applied AI', text: 'Models that run real steps of your process. Not a chatbot in the footer — an agent that opens tickets, writes emails, updates the CRM.' }] },
  specialist: { eyebrow: '04 specialist', title: 'Software, AI and automation', emphasis: 'already running.', paragraph: 'More than 20 projects delivered in custom software, applied AI and operations automation. Below, three flows we built — live simulation, the way they run in production.', stats: [{ value: '+20', label: 'projects delivered' }, { value: '03', label: 'fronts — software, ai, automation' }, { value: '02', label: 'business days to reply' }], tabs: [{ label: '01 WHATSAPP CHATBOT', text: 'Customer sends a message, the bot qualifies, books and pushes to the CRM. Nobody on the team touches it.' }, { label: '02 REPETITIVE AI', text: 'The AI reads, classifies and fills in what used to be copy and paste. Runs overnight.' }, { label: '03 OPERATIONS DASHBOARD', text: 'Sales, operations and finance in the same dashboard. One number, one source of truth.' }], demo: 'DEMO', cta: 'Talk to a specialist →', note: 'REPLIES ON WHATSAPP · MON–FRI, BUSINESS HOURS', chatbot: { customer: ["Hi, I'd like a quote", 'Automation', "Order entry, it's all manual"], bot: ['Of course! Is it for custom software, AI or automation?', 'Perfect. Which process is slowing you down today?', 'Got it. Booked you with a specialist: Thursday, 3pm. ✓'] }, repetitive: { rows: ['invoice', 'customer record', 'reconciliation', 'collection email', 'update CRM', 'report'], counter: 'RECORDS PROCESSED TODAY' }, dashboard: { currency: 'R$184.2K', percent: '92%' } },
  contact: { eyebrow: '05 contact', title: 'Got an operation', emphasis: 'to fix?', paragraph: "Write directly: tell us which process is stuck and what you've already tried. A real person replies, within two business days.", instagram: 'instagram ↗', pkg: 'pkg partnership ↗', brief: 'send a brief ↗' },
  footer: { contact: 'contact', social: 'social', studio: 'studio', location: 'BRAZIL, REMOTE', copy: '© 2026 aymar · technology arrives before the problem.' },
  whatsapp: "Hi! I came from the aymar website. I'd like to talk about my company's operation.", mailSubject: 'Aymar proposal',
  projects: [{ title: 'Criar SaaS', meta: 'digital product · lead capture', badge: 'saas launch', category: 'digital product · lead capture' }, { title: 'Dra. Aline', meta: 'healthcare · authority', badge: 'landing page', category: 'healthcare · authority' }, { title: 'Copie AI', meta: 'ai · launch', badge: 'ai launch', category: 'ai · launch' }, { title: 'Jessica', meta: 'info product · conversion', badge: 'landing page', category: 'info product · conversion' }, { title: 'Master Class', meta: 'event · registration', badge: 'event page', category: 'event · registration' }, { title: 'Mentoria Caio Martins', meta: 'mentorship · high ticket', badge: 'sales page', category: 'mentorship · high ticket' }, { title: 'Isaque Mota', meta: 'personal brand · conversion', badge: 'landing page', category: 'personal brand · conversion' }, { title: 'Primeira Assinatura em 24h', meta: 'digital product · conversion', badge: 'sales page', category: 'digital product · conversion' }]
};
